FZJ-INM1-BDA/siibra-explorer

src/ui/atlasLayerWidget/alwContainer/alwContainer.template.html
src/ui/databrowserModule/databrowser/databrowser.template.html
src/util/directives/delayEvent.directive.ts

sometimes does not show the corresponding panel

bugfix: clicking on parcellation layer widget

---

src/ui/nehubaContainer/nehubaContainer.template.html

buggy behavoiur: on double tap, the browser zooms out.

bugfix: viewport size on mobile buggy

---

src/atlasViewer/atlasViewer.template.html
src/components/fabSpeedDial/fabSpeedDialChild.directive.ts
src/components/fabSpeedDial/fabSpeedDialContainer.directive.ts
src/components/fabSpeedDial/fabSpeedDialTrigger.directive.ts
src/services/stateStore.service.spec.ts
src/ui/nehubaContainer/nehubaContainer.component.ts
src/ui/nehubaContainer/nehubaContainer.style.css
src/ui/nehubaContainer/nehubaContainer.template.html
src/ui/signinBanner/signinBanner.components.ts
src/ui/signinBanner/signinBanner.style.css
src/ui/signinBanner/signinBanner.template.html
src/ui/viewerStateController/regionSearch/regionSearch.component.ts

bugfix: touch interface mesh loading scrn persist
bugfix: touch interface side panel does not scroll
bugfix: speed dail pointer evts when hidden
bugfix: cluttered signin panel in small form factor
chore: remove console logs

misc bug fixes

---

src/atlasViewer/atlasViewer.urlUtil.ts
src/services/effect/effect.ts
src/services/state/viewerState.store.helper.ts
src/ui/nehubaContainer/nehubaContainer.component.ts
src/ui/nehubaContainer/nehubaContainer.template.html
src/ui/parcellationRegion/region.base.ts
src/ui/parcellationRegion/region.directive.ts
src/ui/ui.module.ts

bugfix: catch malformed region select
bugfix: reset region select on parc toggle
bugfix: extra layer selector now populates crucial info
chore: reenable removing of extra layer/region

misc bugfixes and chore

---

src/ui/databrowserModule/util/datasetIsFaved.pipe.ts
src/ui/nehubaContainer/nehubaContainer.component.ts
src/ui/nehubaContainer/nehubaContainer.style.css
src/ui/nehubaContainer/nehubaContainer.template.html

bugfix: pipe when dataentry undefined
bugfix: spatial data undefined
ui: region placeholder
fix regression: conn browser

chore: ui minor issues

---

src/atlasViewer/atlasViewer.template.html
src/res/ext/atlas/atlas_allenMouse.json
src/res/ext/atlas/atlas_multiLevelHuman.json
src/res/ext/atlas/atlas_waxholmRat.json
src/theme.scss
src/ui/nehubaContainer/nehubaContainer.template.html
src/ui/signinBanner/signinBanner.style.css
src/util/pureConstant.service.ts

chore: greater diff side drawer
chore: rearrange signin icons
chore: sort atlas

chore: minor ui tweaks

---

src/res/css/extra_styles.css
src/ui/nehubaContainer/nehubaContainer.component.ts
src/ui/nehubaContainer/nehubaContainer.style.css
src/ui/nehubaContainer/nehubaContainer.template.html
src/ui/parcellationRegion/region.base.ts
src/ui/parcellationRegion/regionMenu/regionMenu.component.spec.ts
src/ui/parcellationRegion/regionMenu/regionMenu.style.css
src/ui/parcellationRegion/regionMenu/regionMenu.template.html
src/util/directives/counter.directive.ts
src/util/util.module.ts

chore: reordered explore in other tmpl
chore: explore in other tmpl btns smaller
chore: regional features show tally

chore UI tweaks

---

docs/releases/v2.0.0.md
docs/releases/v2.3.0.md
src/res/ext/MNI152.json
src/res/ext/atlas/atlas_multiLevelHuman.json
src/services/state/viewerState.store.helper.ts
src/ui/atlasLayerSelector/atlasLayerSelector.template.html
src/ui/databrowserModule/singleDataset/detailedView/singleDataset.template.html
src/ui/databrowserModule/singleDataset/singleDataset.base.ts
src/ui/nehubaContainer/nehubaContainer.component.spec.ts
src/ui/parcellationRegion/region.base.ts
src/ui/parcellationRegion/regionMenu/regionMenu.component.spec.ts
src/ui/parcellationRegion/regionMenu/regionMenu.template.html
src/ui/ui.module.ts

chore: fixed typo: cytocarchitechtonic
feat: if no publication, show authors in dataset card
chore: fixed name of ref template ICBM 152
feat: allow customise label of origin datasets

chore minor tweaks

---

src/atlasViewer/atlasViewer.template.html
src/glue.spec.ts
src/glue.ts
src/main.module.ts
src/res/css/extra_styles.css
src/services/state/uiState.store.helper.ts
src/services/state/uiState/actions.ts
src/services/state/uiState/selectors.ts
src/services/state/viewerState.store.helper.ts
src/services/state/viewerState/selectors.ts
src/ui/databrowserModule/constants.ts
src/ui/databrowserModule/databrowser/databrowser.component.ts
src/ui/databrowserModule/index.ts
src/ui/databrowserModule/preview/previewComponentWrapper/previewCW.component.ts
src/ui/databrowserModule/pure.spec.ts
src/ui/databrowserModule/pure.ts
src/ui/nehubaContainer/statusCard/statusCard.template.html
src/ui/parcellationRegion/region.base.ts
src/ui/parcellationRegion/regionMenu/regionMenu.template.html
src/ui/ui.module.ts

feat: show pmap as chip
refactor: uiState.store
chore: condense region actions

chore: ui tweaks

---

src/atlasViewer/atlasViewer.template.html
src/ui/databrowserModule/databrowser/databrowser.component.ts
src/ui/databrowserModule/databrowser/databrowser.template.html
src/ui/databrowserModule/preview/previewCard/previewCard.style.css
src/ui/databrowserModule/preview/previewCard/previewCard.template.html
src/ui/databrowserModule/singleDataset/detailedView/singleDataset.component.ts
src/ui/databrowserModule/singleDataset/detailedView/singleDataset.template.html
src/ui/nehubaContainer/nehubaContainer.template.html
src/ui/parcellationRegion/regionMenu/regionMenu.style.css
src/ui/parcellationRegion/regionMenu/regionMenu.template.html

bugfix: restore mat chip for origin ds
feat: allow regional features list to be toggled
chore: prettify header banner
feat: show dataset card in iav preview

feat + chore

---

docs/releases/v2.2.5.md
src/ui/nehubaContainer/statusCard/statusCard.component.spec.ts
src/ui/nehubaContainer/statusCard/statusCard.component.ts
src/ui/nehubaContainer/statusCard/statusCard.template.html

* bugfix: statuspanel goto pos voxel flag ineffective
* [skip ci] release notes

bugfix: statuspanel goto pos voxel flag ineffective (#619)

---

.travis.yml
docs/releases/v2.2.6.md
webpack.staticassets.js

chore: updated travis
bugfix: kg dataset previewer URL

bugfix + chore

---

src/atlasViewer/atlasViewer.component.ts
src/atlasViewer/atlasViewer.template.html
src/res/ext/atlas/atlas_allenMouse.json
src/res/ext/atlas/atlas_waxholmRat.json
src/services/state/viewerState.store.helper.ts
src/services/state/viewerState/selectors.spec.ts
src/services/state/viewerState/selectors.ts
src/ui/atlasLayerSelector/atlasLayerSelector.component.ts
src/ui/parcellationRegion/region.base.ts
webpack.aot.js

feat: added version selector
chore: updated aot build

feat: added version selector

---

src/glue.spec.ts
src/glue.ts
src/ui/databrowserModule/preview/preview.base.ts

bugfix: gracefully handle prv -> 404

---

deploy/csp/index.js
src/atlasViewer/atlasViewer.template.html
src/res/css/extra_styles.css
src/util/directives/stopPropagation.directive.ts

bugfix: csp fontSrc
bugfix: remove additional layers stop event prop
uifix: remove box shadow for version selection
chore: pointer-events css rule & stop prop arg type

Misc minor bugfixes & chores

---

src/atlasViewer/atlasViewer.apiService.service.ts
src/atlasViewer/mouseOver.directive.ts
src/plugin_examples/plugin_api.md
src/services/state/uiState.store.ts
src/services/state/viewerState.store.helper.ts
src/services/state/viewerState.store.ts
src/services/state/viewerState/actions.ts
src/services/state/viewerState/selectors.ts
src/ui/nehubaContainer/landmarkUnit/landmarkUnit.component.ts
src/ui/nehubaContainer/landmarkUnit/landmarkUnit.template.html
src/ui/nehubaContainer/nehubaContainer.component.spec.ts
src/ui/nehubaContainer/nehubaContainer.component.ts
src/ui/nehubaContainer/nehubaContainer.template.html
src/ui/nehubaContainer/nehubaViewer/nehubaViewer.component.ts
src/ui/nehubaContainer/nehubaViewerInterface/nehubaViewerInterface.directive.ts

feat: 3d landmarks now can inherit colours
feat: interactiveViewer.viewerHandle.mouseOverNehubaUI now allows customLandmarks enter/leave state to be monitored

feat: custom landmarks can now inherit colours & more api coverage

---

src/glue.ts
src/res/ext/MNI152.json
src/res/ext/colin.json
src/ui/parcellationRegion/regionMenu/regionMenu.template.html

bugfix: preview now uses schema as well as id
bugfix: fix gapmap id

Fixing gapmap pmap preview

---

src/atlasViewer/atlasViewer.component.ts
src/atlasViewer/mouseOver.directive.ts
src/res/ext/allenMouse.json
src/services/state/uiState/selectors.spec.ts
src/services/state/uiState/selectors.ts

fixes https://trello.com/c/0lm4oOMb/25-allen-ccf-v3-do-not-allow-root-to-be-selected

chore: disallow allen v3 root to be selected

---

deploy/constants.js
src/res/ext/bigbrain.json

bugfix: id for hoc3v and hoc5
bugfix: path in deploy/constant.js

Bugfix Big Brain fully mapped region ID

---

common/constants.js
e2e/protractor.conf.js
e2e/src/advanced/browsingForDatasets.prod.e2e-spec.js
e2e/src/advanced/nonAtlasImages.prod.e2e-spec.js
e2e/src/util.js
src/atlasViewer/atlasViewer.component.ts
src/atlasViewer/atlasViewer.template.html
src/atlasViewer/atlasViewer.urlUtil.spec.ts
src/glue.spec.ts
src/glue.ts
src/main.module.ts
src/services/state/uiState.store.ts
src/services/state/uiState/common.ts
src/services/state/uiState/selectors.ts
src/services/state/uiState/ui.effects.ts
src/services/state/viewerState/selectors.ts
src/services/stateStore.helper.ts
src/services/stateStore.service.ts
src/ui/databrowserModule/constants.ts
src/ui/databrowserModule/preview/shownPreviews.directive.ts
src/ui/nehubaContainer/nehubaContainer.component.ts
src/ui/nehubaContainer/nehubaContainer.template.html
src/ui/nehubaContainer/nehubaViewer/nehubaViewer.component.ts
src/ui/nehubaContainer/nehubaViewerInterface/nehubaViewerInterface.directive.ts
src/ui/viewerStateController/viewerState.useEffect.ts

bugfix: appearance of nonAtlasVolumes
bugfix: e2e non atlas volumes
chore: misc fixes

Bugfix: non atlas volumes

---

common/constants.js
src/services/state/ngViewerState.store.ts
src/services/state/ngViewerState/selectors.ts
src/ui/config/config.component.ts
src/ui/config/currentLayout/currentLayout.component.ts
src/ui/nehubaContainer/maximisePanelButton/maximisePanelButton.component.ts
src/ui/nehubaContainer/nehubaContainer.component.spec.ts
src/ui/nehubaContainer/nehubaContainer.component.ts
src/ui/nehubaContainer/nehubaContainer.template.html
src/ui/nehubaContainer/nehubaViewerInterface/nehubaViewerInterface.directive.ts
src/ui/nehubaContainer/touchSideClass.directive.ts
src/util/pipes/getNthElement.pipe.ts
src/util/pipes/parseAsNumber.pipe.ts
src/util/util.module.ts

fixes #680
also relevant: #682

bugfix: viewer control not correctly setup

---

src/services/state/ngViewerState.store.helper.ts
src/services/state/ngViewerState.store.ts
src/services/state/ngViewerState/selectors.ts
src/services/state/viewerState/selectors.ts
src/ui/config/config.component.ts
src/ui/databrowserModule/databrowser.service.ts
src/ui/nehubaContainer/nehubaContainer.component.ts
src/ui/nehubaContainer/nehubaViewerInterface/nehubaViewerInterface.directive.spec.ts
src/ui/nehubaContainer/nehubaViewerInterface/nehubaViewerInterface.directive.ts
src/ui/nehubaContainer/util.ts

chore: retain panel order and mode on switch tmpl

---

src/atlasViewer/atlasViewer.apiService.service.ts
src/atlasViewer/atlasViewer.constantService.service.ts
src/main.module.ts
src/services/effect/pluginUseEffect.ts
src/services/state/viewerState.store.helper.ts
src/services/state/viewerState.store.ts
src/services/state/viewerState/actions.ts
src/services/state/viewerState/selectors.ts
src/ui/nehubaContainer/nehubaContainer.component.spec.ts
src/ui/nehubaContainer/nehubaContainer.component.ts
src/ui/viewerStateController/viewerState.base.ts
src/ui/viewerStateController/viewerState.useEffect.spec.ts
src/ui/viewerStateController/viewerState.useEffect.ts
src/util/pureConstant.service.ts

Bugfix ref space spatial xform

---

e2e/src/selecting/region.prod.e2e-spec.js
src/atlasViewer/atlasViewer.component.ts

chore: allow only one region to be selected

---

common/helpOnePager.md
deploy/app.js
deploy/package.json
deploy/quickstart/index.js
e2e/src/layout/home.prod.e2e-spec.js
e2e/src/util.js
e2e/util/selenium/base.js
src/components/markdown/markdown.component.ts
src/ui/helpOnePager/helpOnePager.component.spec.ts
src/ui/helpOnePager/helpOnePager.component.ts
src/ui/helpOnePager/helpOnePager.template.html
src/ui/signinBanner/signinBanner.components.ts
src/ui/signinBanner/signinBanner.template.html
src/ui/ui.module.ts

feat: quick start one pager
chore: fix e2e base class
activate by `?` or `[click]` on (?)

Feat: add quick start one pager

---

common/constants.js
e2e/src/selecting/region.prod.e2e-spec.js
e2e/util/selenium/layout.js
e2e/util/selenium/util.js
src/services/effect/effect.spec.ts
src/services/effect/effect.ts
src/ui/atlasDropdown/atlasDropdown.component.ts
src/ui/atlasDropdown/atlasDropdown.template.html

bugfix: reset region selection on atlas change

---

src/services/state/viewerState.store.ts
src/services/state/viewerState/actions.ts
src/services/state/viewerState/selectors.ts
src/ui/nehubaContainer/statusCard/statusCard.component.spec.ts
src/ui/nehubaContainer/statusCard/statusCard.component.ts

bugfix: status panel causes navigation state error
chore: also partial address #682

bugfix: status panel causes nav errors (#707)

---

e2e/src/selecting/atlas.prod.e2e-spec.js
e2e/util/selenium/iav.js
e2e/util/selenium/layout.js
src/services/state/viewerState.store.ts

bugfix: multilevel human parc name not shown

---

deploy/datasets/util.js
e2e/util/selenium/layout.js
src/res/css/extra_styles.css
src/res/ext/atlas/atlas_multiLevelHuman.json
src/services/state/viewerState.store.helper.spec.ts
src/services/state/viewerState.store.helper.ts
src/services/state/viewerState/selectors.ts
src/ui/atlasLayerSelector/atlasLayerSelector.component.ts
src/ui/nehubaContainer/nehubaViewerInterface/nehubaViewerInterface.directive.ts
src/ui/parcellationRegion/region.base.spec.ts
src/ui/parcellationRegion/region.base.ts
src/ui/parcellationRegion/regionMenu/regionMenu.component.spec.ts

- only show regions of the latest version

bugfix: show only relevant regions in other tmpl spaces

---

deploy/atlas/sanity.spec.js
e2e/src/advanced/browsingForDatasets.prod.e2e-spec.js
e2e/src/selecting/atlas.prod.e2e-spec.js
e2e/src/selecting/region.prod.e2e-spec.js
e2e/util/selenium/iav.js
e2e/util/selenium/layout.js
src/res/ext/waxholmRatV2_0.json
src/services/state/viewerState.store.helper.ts
src/ui/atlasLayerSelector/atlasLayerSelector.template.html
src/ui/nehubaContainer/nehubaViewer/nehubaViewer.component.spec.ts
src/ui/nehubaContainer/nehubaViewer/nehubaViewer.component.ts

Bugfix mesh not loading x not removing layer

---

deploy/app.js
deploy/app.spec.js
deploy/csp/index.js
deploy/datasets/index.js
src/ui/databrowserModule/singleDataset/sideNavView/sDsSideNavView.template.html
src/ui/regionalFeatures/featureExplorer/featureExplorer.component.ts
src/ui/regionalFeatures/featureExplorer/featureExplorer.template.html
src/util/pipes/arrayContains.pipe.ts
src/util/util.module.ts

bugfix: ieeg panel update
bugfix: ieeg electrode selection
chore: csp tightening
chore: ready flag for dataset fetch

bugfix: ieeg panel update & ieeg selection

---

deploy/auth/index.js
deploy/auth/index.spec.js
deploy/auth/util.js
deploy/auth/util.spec.js
deploy/datasets/index.js
deploy/datasets/util.js
src/main.module.ts
src/ui/databrowserModule/databrowser.service.ts
src/ui/databrowserModule/databrowser/databrowser.component.ts
src/ui/databrowserModule/kgSingleDatasetService.service.ts

chore: decouple get public access token
bugfix: only use side panel dataset display locally
chore: remove unused prop data browser service
feat: memoize get req for dataset info

bugfix: properly implement ready probe

---

src/ui/regionalFeatures/singleFeatures/base/regionFeature.base.ts
src/ui/regionalFeatures/singleFeatures/iEEGRecordings/iEEGRecordings/iEEGRecordings.component.ts

fixes #744 
still needs tests to prevent regression

bugfix: ieeg view change not detecting

---

README.md
deploy/csp/index.js
deploy/datasets/query.js
deploy/regionalFeatures/index.js
src/atlasViewer/pluginUnit/pluginFactory.directive.ts
src/index.html
src/ui/regionalFeatures/regionalFeature.service.ts
src/ui/regionalFeatures/singleFeatures/receptorDensity/receptorDensity/receptorDensity.style.css
src/ui/regionalFeatures/singleFeatures/receptorDensity/receptorDensity/receptorDensity.template.html

using updated kg dataset previewer from 1.1.4 to 1.1.5.
d3 dsv.parse uses unsafe eval, which is not compatible with csp

fix dataset preview csp issues

---

src/components/components.module.ts
src/components/spinner/spinner.component.ts
src/components/spinner/spinner.template.html
src/ui/databrowserModule/databrowser.service.ts
src/ui/databrowserModule/databrowser/databrowser.template.html
src/ui/databrowserModule/preview/datasetPreviews/datasetPreviewsList/datasetPreviewList.template.html
src/ui/databrowserModule/singleDataset/detailedView/singleDataset.template.html
src/ui/databrowserModule/singleDataset/listView/singleDatasetListView.template.html
src/ui/databrowserModule/singleDataset/sideNavView/sDsSideNavView.template.html
src/ui/nehubaContainer/nehubaContainer.style.css
src/ui/nehubaContainer/nehubaContainer.template.html
src/ui/nehubaContainer/splashScreen/splashScreen.template.html
src/ui/regionalFeatures/singleFeatures/iEEGRecordings/iEEGRecordings/iEEGRecordings.template.html
src/ui/regionalFeatures/singleFeatures/iEEGRecordings/module.ts

chore: added dedicated spinner cmp
bugfix: when dataentry has not method field defined
chore: added citation/contributor for side nav dataset card
chore: added spinner when loading: feature/dataset/etc

chore: cosmetic updates

---

src/ui/regionalFeatures/singleFeatures/receptorDensity/receptorDensity/receptorDensity.component.ts
src/ui/regionalFeatures/singleFeatures/receptorDensity/receptorDensity/receptorDensity.template.html

chore: added click interactivity to receptor fp
chore: added no pr or ar message

chore/feat: receptor density widget

---

src/ui/signinBanner/signinBanner.components.ts
src/util/directives/keyDownListener.directive.ts

bugfix: h key no longer breaks UI

---

common/constants.js
e2e/src/advanced/browsingForDatasets.prod.e2e-spec.js
src/ui/databrowserModule/databrowser/databrowser.component.ts
src/ui/databrowserModule/modalityPicker/modalityPicker.component.ts
src/ui/databrowserModule/modalityPicker/modalityPicker.template.html

bugfix: modality not populated properly

---

common/constants.js
e2e/src/advanced/favDatasets.prod.e2e-spec.js
e2e/util/selenium/layout.js
src/ui/databrowserModule/singleDataset/detailedView/singleDataset.template.html
src/ui/signinBanner/signinBanner.components.ts
src/ui/signinBanner/signinBanner.template.html

bugfix: (un)pin modal dataset

---

src/messaging/module.ts

add3dlandmarks, remove3dlandmarks

chore: adding more messaging API

---

src/ui/databrowserModule/singleDataset/sideNavView/sDsSideNavView.template.html
src/ui/nehubaContainer/nehubaContainer.template.html
src/ui/regionalFeatures/singleFeatures/iEEGRecordings/iEEGRecordings/iEEGRecordings.template.html

chore: minor tweaks to ieeg
chore: minor tweaks to region menu ui

Remove contact pts in iEEG, auto collapse feature panel, unify side panel ui

---

src/res/ext/MNI152.json
src/res/ext/MNI152NehubaConfig.json
src/res/ext/atlas/atlas_multiLevelHuman.json
src/res/ext/bigbrain.json
src/res/ext/colin.json
src/res/ext/colinNehubaConfig.json
src/services/effect/effect.spec.ts

(breaks tests, need to add fullId to regions, need to add origin datasets)

exmpt julich brain v2.5

---

src/ui/databrowserModule/databrowser.module.ts
src/ui/databrowserModule/singleDataset/singleDataset.base.ts
src/ui/databrowserModule/singleDataset/singleDataset.directive.ts
src/ui/nehubaContainer/nehubaContainer.template.html
src/ui/parcellationRegion/regionMenu/regionMenu.component.spec.ts
src/ui/parcellationRegion/regionMenu/regionMenu.template.html
src/util/util.module.ts

feat: add desc to region side panel
feat: add open kg link in rg side panel
feat: add pin dataset to rg side panel

feat: adding additional features to region side nav

---

deploy/datasets/importIBS.js
deploy/datasets/query.js
src/ui/databrowserModule/singleDataset/singleDataset.base.ts

chore: filter dataset filtering first words
chore: reenable ibc datasets

chore: dataset fetching (filter out maps, reenable ibc datasets)

---

src/ui/regionalFeatures/singleFeatures/iEEGRecordings/iEEGRecordings/iEEGRecordings.template.html
src/ui/regionalFeatures/singleFeatures/receptorDensity/receptorDensity/receptorDensity.template.html

ieeg and receptor feature component minor ui tweaks

Chore regional feature minor fixes

---

src/ui/nehubaContainer/nehubaContainer.component.ts
src/ui/parcellationRegion/region.base.ts
src/ui/parcellationRegion/regionMenu/regionMenu.template.html

Bugfix UI issues

---

deploy/saneUrl/index.js

bugfix: remove rate limiting for get req

---

.github/workflows/e2e.yml
Dockerfile
common/constants.js
e2e/src/advanced/pluginApi.prod.e2e-spec.js
e2e/src/advanced/urlParsing.prod.e2e-spec.js
e2e/src/navigating/btnZoomInOut.prod.e2e-spec.js
e2e/src/selecting/region.prod.e2e-spec.js
e2e/src/selecting/template.prod.e2e-spec.js
e2e/util/selenium/layout.js
src/atlasComponents/uiSelectors/atlasLayerSelector/atlasLayerSelector.template.html
src/atlasViewer/atlasViewer.style.css
src/viewerModule/viewerCmp/viewerCmp.template.html

chore: partial fix e2e tests

---

src/ui/ui.module.ts

[bugfix] high DPR screenshot

---

common/util.js
common/util.spec.js
docs/releases/v2.4.0.md
src/atlasComponents/parcellationRegion/region.base.ts
src/viewerModule/nehuba/nehubaViewer/nehubaViewer.component.ts

bugfix: unique rgb for regions when rgb is absent

---

deploy/package.json
docs/releases/v2.4.0.md

chore: updated openid client
chore: remove unneeded dep
fixes #696

chore update dependencies

---

deploy/app.spec.js
deploy/user/index.js
deploy/user/index.spec.js
docs/releases/v2.4.0.md
src/auth/auth.service.spec.ts
src/auth/auth.service.ts
src/services/state/ngViewerState.store.spec.ts
src/services/state/ngViewerState.store.ts
src/viewerModule/viewerCmp/viewerCmp.template.html

do not cause network error if user is not signed in

---

deploy/csp/index.js
src/index.html
src/viewerModule/threeSurfer/threeSurferGlue/threeSurfer.component.ts
src/viewerModule/threeSurfer/threeSurferGlue/threeSurfer.style.css
src/viewerModule/threeSurfer/threeSurferGlue/threeSurfer.template.html

chore: updated threesurfer

---

.github/workflows/e2e.yml
e2e/src/advanced/history.prod.e2e-spec.js
src/atlasComponents/splashScreen/splashScreen/splashScreen.component.ts
src/services/effect/effect.spec.ts
src/services/effect/effect.ts
src/services/effect/newTemplate.effect.ts
src/services/state/userConfigState.store.ts
src/services/state/viewerState.store.ts
src/services/stateStore.service.ts
src/util/pureConstant.service.ts
src/viewerModule/viewerCmp/viewerCmp.template.html

bugfix: history should remove viewer when fit

---

package.json
src/messaging/nmvSwc/index.ts

now expects all units in microns

chore: fix swc support

---

docs/releases/v2.4.0.md
src/res/ext/allenMouse.json
src/viewerModule/nehuba/constants.ts
src/viewerModule/nehuba/mesh.service.spec.ts
src/viewerModule/nehuba/mesh.service.ts
src/viewerModule/nehuba/nehubaViewer/nehubaViewer.component.spec.ts
src/viewerModule/nehuba/nehubaViewer/nehubaViewer.component.ts
src/viewerModule/nehuba/nehubaViewerGlue/nehubaViewerGlue.component.ts

feat: only load top level mesh(es)

---

e2e/src/advanced/urlParsing.prod.e2e-spec.js
e2e/src/selecting/template.prod.e2e-spec.js
package.json
src/messaging/nmvSwc/index.ts
src/messaging/nmvSwc/type.ts
src/messaging/service.ts

bugfix: e2e tests
bugfix: export nehuba breaking swc datasrc
chore: add more meaning error msg

bugfixes (swc data src & e2e tests)

---

docs/releases/v2.4.0.md
src/viewerModule/viewerCmp/viewerCmp.template.html

Chore chip wrapping

---

docs/releases/v2.4.0.md
package.json
src/services/state/viewerState.store.helper.spec.ts
src/services/state/viewerState.store.helper.ts

- bumped export-nehuba version to remove logging
- added quick tour release notes
- bugfix #831

[chore] minor fixes

---

src/atlasComponents/parcellation/regionSearch/regionSearch.component.ts
src/services/effect/effect.ts
src/services/state/viewerState.store.ts
src/services/state/viewerState/actions.ts
src/services/stateStore.service.ts
src/viewerModule/componentStore.ts
src/viewerModule/constants.ts
src/viewerModule/viewerCmp/viewerCmp.component.ts
src/viewerModule/viewerCmp/viewerCmp.template.html

fixes #760 
chore: side nav panel state
chore: refactor store action

chore: side nav panel state persist on browse dataset

---

Dockerfile
build_env.md
src/atlasComponents/regionalFeatures/bsFeatures/constants.ts
src/atlasComponents/regionalFeatures/bsFeatures/index.ts
src/atlasComponents/regionalFeatures/bsFeatures/receptor/ar/autoradiograph.component.ts
src/atlasComponents/regionalFeatures/bsFeatures/receptor/base.ts
src/atlasComponents/regionalFeatures/bsFeatures/receptor/entry/entry.component.ts
src/atlasComponents/regionalFeatures/bsFeatures/receptor/entry/entry.template.html
src/atlasComponents/regionalFeatures/bsFeatures/receptor/fp/fp.component.ts
src/atlasComponents/regionalFeatures/bsFeatures/receptor/hasReceptor.directive.ts
src/atlasComponents/regionalFeatures/bsFeatures/receptor/profile/profile.component.ts
src/atlasComponents/regionalFeatures/bsFeatures/receptor/service.ts
src/atlasComponents/regionalFeatures/bsFeatures/receptor/type.ts
src/atlasComponents/regionalFeatures/bsFeatures/service.ts
webpack/webpack.staticassets.js

see https://github.com/FZJ-INM1-BDA/siibra-api/pull/22

chore: rework api call to siibra

---

common/util.js
e2e/protractor.conf.js
src/atlasComponents/parcellationRegion/region.base.spec.ts
src/atlasComponents/parcellationRegion/region.base.ts

> can't we do that here?
> we can get centroids for mni152 and colin left/right, just not a big brain
@xgui3783 Then it should work with the current way. Could be great to get them.

Modify explore in other templates for siibra api

---

package.json
src/atlasComponents/connectivity/connectivityBrowser/connectivityBrowser.component.ts
src/viewerModule/nehuba/nehubaViewerGlue/nehubaViewerGlue.component.spec.ts

This PR is only changing the diagram approach to use canvas and does not contain component cleanup. Cleanup will be done into the next branch.

Dev connectivity canvas

---

deploy/package-lock.json
deploy/package.json
docs/releases/v2.5.2.md
mkdocs.yml
src/routerModule/util.spec.ts
src/routerModule/util.ts
src/util/patchPureConstants.ts
src/util/pureConstant.service.ts
src/util/siibraApiConstants/types.ts

- npm audit
- big brain high resolution
- provide better navigation when nav not provided in url

hotfix: big brain high resolution 

---

.github/workflows/docker_img.yml
Dockerfile
angular.json
deploy/csp/index.js
deploy/package-lock.json
deploy/package.json
deploy/saneUrl/index.js
docs/releases/v2.5.7.md
package.json
src/atlasViewer/atlasViewer.workerService.service.ts
src/environments/environment.common.ts
src/environments/parseEnv.js
src/main-common.ts
src/viewerModule/nehuba/nehubaViewer/nehubaViewer.component.ts

chore: fix csp
chore: added saneurls
chore: improv build
before:
this PR:

[enh] improved build, fixed csp, added saneurls

---

deploy/plugins/index.js
src/api/service.ts
src/plugin/README.md
src/plugin/request.md
src/plugin/tsUtil.js
src/state/atlasSelection/effects.ts
src/viewerModule/nehuba/layerCtrl.service/layerCtrl.service.ts
src/viewerModule/nehuba/nehubaViewer/nehubaViewer.component.ts

bugfix: allow layer transparency to be modified via ng custom layer

feat: allow plugin to add and remove custom layer

---

deploy/csp/index.js
src/atlasComponents/sapiViews/core/parcellation/parcellationVersion.pipe.spec.ts
src/atlasComponents/sapiViews/core/parcellation/parcellationVersion.pipe.ts
src/index.html

chore: update package name
chore: update csp

bugfix: skip deprecated parcellation versions

---

docs/releases/v2.7.7.md
mkdocs.yml
package-lock.json
package.json
src/extra_styles.css

region hierarchy window becomes un-interactable. this PR should address this issue.

hotfix: fixing region hierarchy

---

docs/releases/v2.8.0.md
src/atlasComponents/sapiViews/core/rich/module.ts
src/atlasComponents/sapiViews/core/rich/regionsHierarchy/regionsHierarchy.template.html
src/atlasComponents/sapiViews/core/rich/regionsListSearch/regionListSearch.component.ts
src/atlasComponents/sapiViews/core/rich/regionsListSearch/regionListSearch.stories.ts
src/atlasComponents/sapiViews/core/rich/regionsListSearch/regionListSearch.template.html
src/atlasComponents/sapiViews/core/rich/regionsListSearch/regionListSearchTmpl.directive.ts
src/viewerModule/viewerCmp/viewerCmp.template.html

fixing (mini & hierachy) region search

---

src/features/connectivity/connectivityBrowser/connectivityBrowser.component.spec.ts
src/features/entry/entry.component.spec.ts
src/routerModule/routeStateTransform.service.spec.ts
src/routerModule/router.service.spec.ts
src/routerModule/router.service.ts
src/state/atlasSelection/effects.spec.ts
src/state/atlasSelection/effects.ts
src/viewerModule/nehuba/mesh.service/mesh.service.spec.ts
src/viewerModule/nehuba/nehubaViewer/nehubaViewer.component.spec.ts

fix most of tests

---

docs/releases/v2.11.0.md
src/atlasComponents/sapiViews/core/rich/regionsHierarchy/regionsHierarchy.component.ts
src/atlasComponents/sapiViews/core/rich/regionsListSearch/regionListSearch.component.ts
src/atlasComponents/userAnnotations/tools/poly/poly.template.html
src/components/flatHierarchy/treeView/treeView.component.ts
src/components/flatHierarchy/treeView/treeView.template.html
src/extra_styles.css
src/state/atlasSelection/actions.ts
src/state/atlasSelection/store.ts
src/util/side-panel/side-panel.component.html
src/util/side-panel/side-panel.component.scss
src/util/side-panel/side-panel.component.spec.ts
src/util/side-panel/side-panel.component.ts
src/util/util.module.ts
src/viewerModule/nehuba/nehubaViewerGlue/nehubaViewerGlue.component.ts
src/viewerModule/viewerCmp/viewerCmp.component.ts
src/viewerModule/viewerCmp/viewerCmp.template.html

fixes https://github.com/FZJ-INM1-BDA/siibra-explorer/issues/1248 supercedes #1255

feat: allow multi region selection

---

docs/releases/v2.11.0.md
src/atlasComponents/sapi/sapi.service.ts
src/atlasComponents/sapi/schemaV3.ts
src/atlasComponents/sapiViews/module.ts
src/atlasComponents/sapiViews/volumes/point-assignment/point-assignment.component.html
src/atlasComponents/sapiViews/volumes/point-assignment/point-assignment.component.scss
src/atlasComponents/sapiViews/volumes/point-assignment/point-assignment.component.spec.ts
src/atlasComponents/sapiViews/volumes/point-assignment/point-assignment.component.ts
src/atlasComponents/sapiViews/volumes/volumes.module.ts
src/atlasComponents/userAnnotations/tools/type.ts
src/atlasViewer/atlasViewer.component.ts
src/contextMenuModule/service.ts
src/state/atlasSelection/actions.ts
src/state/atlasSelection/const.ts
src/state/atlasSelection/effects.ts
src/state/atlasSelection/selectors.ts
src/state/atlasSelection/store.ts
src/util/df-to-ds.pipe.spec.ts
src/util/df-to-ds.pipe.ts
src/util/fn.ts
src/util/pretty-present.pipe.spec.ts
src/util/pretty-present.pipe.ts
src/util/types.ts
src/util/util.module.ts
src/viewerModule/viewerCmp/viewerCmp.component.ts
src/viewerModule/viewerCmp/viewerCmp.template.html

feat: allow pt assignment

---

docs/releases/v2.11.1.md
src/atlasComponents/sapi/sapi.service.ts
src/atlasComponents/sapi/translateV3.ts
src/state/atlasSelection/util.ts
src/state/index.ts
src/state/userInteraction/effects.ts
src/viewerModule/nehuba/layerCtrl.service/layerCtrl.service.ts
src/viewerModule/nehuba/mesh.service/mesh.service.spec.ts
src/viewerModule/nehuba/mesh.service/mesh.service.ts

fix: reset selected feature on atlas/parcellation/template reset
fix: julich brain 2.9 in colin 27 now shows meshes

fix: cortical layer

---

.github/workflows/ci.yml
.github/workflows/docker_img.yml
.github/workflows/e2e.yml
.github/workflows/manual_e2e.yml
.github/workflows/release.yml
.github/workflows/repo_sync_ebrains.yml
docs/releases/v2.11.2.md
src/messaging/service.ts
src/widget/service.ts

maint: update CI version
maint: remove deprecated use of cmpfactory

fix: filter by message namespace

---

docs/releases/v2.11.3.md
mkdocs.yml
package-lock.json
package.json
src/atlasComponents/sapi/schemaV3.ts
src/atlasComponents/sapiViews/volumes/point-assignment/point-assignment.component.html
src/atlasComponents/sapiViews/volumes/point-assignment/point-assignment.component.ts
src/routerModule/routeStateTransform.service.spec.ts
src/routerModule/routeStateTransform.service.ts
src/routerModule/type.ts
src/util/fn.ts

behind the scenes: using hashed region name for selected region URL encoding

fix: point assignment for label parcellations

---

deploy/app.js
e2e/checklist.md
src/atlasComponents/sapiViews/volumes/point-assignment/point-assignment.component.ts
src/share/saneUrl/saneUrl.component.spec.ts
src/util/side-panel/side-panel.component.spec.ts
src/viewerModule/viewerCmp/viewerCmp.component.ts

fix: do not show point assignment on a face

maint: add cache to favicon

---

docs/releases/v2.11.2.md
src/atlasComponents/sapiViews/core/parcellation/module.ts
src/atlasComponents/sapiViews/core/parcellation/parcellationVis.effect.ts
src/atlasComponents/sapiViews/core/rich/ATPSelector/wrapper/wrapper.component.ts
src/viewerModule/threeSurfer/threeSurferGlue/threeSurfer.component.ts

fix: threesurfer toggle delineation

---

docs/releases/v2.12.0.md
src/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
src/features/connectivity/connectivityBrowser/connectivityBrowser.template.html
src/util/periodic.service.ts

fix: connectivity matrix input fire rate
fix: conn busy spinner
feat: added selected subject & dataset

maint: simplify periodic service

---

src/atlasComponents/annotations/annotation.service.ts
src/atlasComponents/sapi/sapi.service.ts
src/util/periodic.service.ts

maint: bump siibra api version

fix: api addAnnotation

---

angular.json
common/constants.js
deploy/app.js
docs/releases/v2.12.0.md
src/atlasComponents/sapi/sapi.service.ts
src/atlasViewer/atlasViewer.component.ts
src/viewerModule/nehuba/mesh.service/mesh.service.spec.ts
src/viewerModule/nehuba/nehubaViewer/nehubaViewer.component.spec.ts
src/viewerModule/nehuba/nehubaViewer/nehubaViewer.component.ts
third_party/vanilla.html

maint: added css to vanilla.html

fix: big brain rubber banding position

---

.eslintrc.js
deploy/csp/index.js
docs/releases/v2.12.1.md
mkdocs.yml
package-lock.json
src/index.html
src/viewerModule/nehuba/nehubaViewer/nehubaViewer.component.ts
src/viewerModule/nehuba/nehubaViewerInterface/nehubaViewerTouch.directive.ts

feat: rgb colormap control
fix: touch control not working

fix: ng layer controller not working

---

.github/workflows/deploy-on-okd.yml
.github/workflows/docker_img.yml
package.json

fix: package version in package.json

---

docs/releases/v2.12.3.md
mkdocs.yml
package.json
src/atlasComponents/sapi/sapi.service.ts
src/atlasComponents/sapiViews/core/region/module.ts
src/atlasComponents/sapiViews/core/rich/regionsHierarchy/regionsHierarchy.component.ts
src/atlasComponents/sapiViews/core/rich/regionsHierarchy/regionsHierarchy.template.html
src/components/flatHierarchy/treeView/treeView.template.html
src/features/guards.ts
src/viewerModule/viewerCmp/viewerCmp.component.ts
src/viewerModule/viewerCmp/viewerCmp.template.html

fix: region selectable

---

docs/releases/v2.12.5.md
mkdocs.yml
package.json
src/atlasComponents/sapi/sapi.service.ts
src/features/entry/entry.component.ts
src/ui/help/about/about.component.ts
src/ui/help/about/about.style.css
src/ui/help/about/about.template.html
src/ui/help/module.ts

feat: added version inspector in UI

feat: enabled connectivity for jba3

---

backend/app/app.py
backend/app/plugin.py

maint: do not log ready endpoint

---

src/atlasComponents/sapi/translateV3.ts

- chenonceau
- wikibrainstem
- salditt
- broca/neun
- new pli mask

Add more meta for voi display

---

.github/workflows/ci.yml
.github/workflows/docker_img.yml
Dockerfile
build_env.md
docs/releases/v2.14.5.md
src/ui/dialogInfo/dialog.directive.ts
src/viewerModule/nehuba/statusCard/statusCard.component.ts
src/viewerModule/nehuba/statusCard/statusCard.template.html

feat: coord edit dialog, on paste, auto parse

---

backend/app/index_html.py
backend/app/sane_url.py
docs/releases/v2.14.5.md
src/atlasComponents/annotations/annotation.service.ts
src/components/coordTextBox/index.ts
src/sharedModules/angularMaterial.exports.ts
src/ui/bottomMenu/bottomMenuCmp/bottomMenu.template.html
src/util/directives/floatingMouseContextualContainer.directive.ts
src/util/directives/mediaQuery.directive.ts
src/util/util.module.ts
src/viewerModule/module.ts
src/viewerModule/nehuba/module.ts
src/viewerModule/nehuba/statusCard/statusCard.component.spec.ts
src/viewerModule/nehuba/statusCard/statusCard.component.ts
src/viewerModule/nehuba/statusCard/statusCard.template.html
src/viewerModule/nehuba/userLayers/userlayerInfo/userlayerInfo.component.ts
src/viewerModule/nehuba/userLayers/userlayerInfo/userlayerInfo.template.html
src/viewerModule/viewerCmp/viewerCmp.template.html

Occassionally, annotation mode does not show the annotation being drawn. 
this PR fixes this issue.

fix: annotation mode

---

docs/releases/v2.14.5.md
src/atlas-download/atlas-download.directive.ts
src/atlasComponents/sapi/sapi.service.ts
src/atlasComponents/sapi/translateV3.ts
src/state/atlasSelection/actions.ts
src/state/atlasSelection/const.ts
src/state/atlasSelection/effects.ts
src/state/atlasSelection/selectors.ts
src/state/atlasSelection/store.ts
src/viewerModule/pipes/nehubaVCtxToBbox.pipe.ts

feat: download atlas with bbox param

feat: download atlas with bbox param, meta.json

---

src/viewerModule/nehuba/config.service/util.ts

added custom sacle for 3d model view of marmoset nm template
added special treatment of lightTheme for marmoset nm template
added special center translate for marmoset nm template
added custom substrate width and height for marmoset nm template

A few special treatment of configuration for Marmoset NM template
